### ISSUE TITLE
Layout bugs

### ISSUE THREAD

**Issue by ed-fast** [the-working-party/bell-newsletter#4]
Browsers/Clients affected
- All web clients on Firefox
- All web clients on IE
- Desktop Outlook

- [ ] Width of entire email incorrect, displays 640px, should be 580px. 
- [ ] Logo indented
- [ ] Phone number in footer is outdented
- [ ] Text below the main content image is floating to the right of the image (outlook desktop)

**Comment by ed-fast** [comment]
![screen shot 2015-04-28 at 9 31 32 am](https://cloud.githubusercontent.com/assets/5318077/7360074/e74dd5b0-ed89-11e4-8fdf-6cf684c3ddb8.png)

**Comment by oksushi** [comment]
Emailed client saying that we are not proceeding.
